// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GreetPackage_SayHello_FullMethodName = "/greet_service_package.GreetPackage/SayHello"
)

// GreetPackageClient is the client API for GreetPackage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetPackageClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type greetPackageClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetPackageClient(cc grpc.ClientConnInterface) GreetPackageClient {
	return &greetPackageClient{cc}
}

func (c *greetPackageClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GreetPackage_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetPackageServer is the server API for GreetPackage service.
// All implementations must embed UnimplementedGreetPackageServer
// for forward compatibility
type GreetPackageServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedGreetPackageServer()
}

// UnimplementedGreetPackageServer must be embedded to have forward compatible implementations.
type UnimplementedGreetPackageServer struct {
}

func (UnimplementedGreetPackageServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetPackageServer) mustEmbedUnimplementedGreetPackageServer() {}

// UnsafeGreetPackageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetPackageServer will
// result in compilation errors.
type UnsafeGreetPackageServer interface {
	mustEmbedUnimplementedGreetPackageServer()
}

func RegisterGreetPackageServer(s grpc.ServiceRegistrar, srv GreetPackageServer) {
	s.RegisterService(&GreetPackage_ServiceDesc, srv)
}

func _GreetPackage_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetPackageServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetPackage_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetPackageServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetPackage_ServiceDesc is the grpc.ServiceDesc for GreetPackage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetPackage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service_package.GreetPackage",
	HandlerType: (*GreetPackageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetPackage_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greet.proto",
}
